// This is a generated file, do not edit!
// Generated by clrex, see https://github.com/ilyapuchka/clrex

import UIKit

enum MyColors {

  static func darkGrayBackgroundColor() -> UIColor {
    return UIColor(red: 0.333333, green: 0.333333, blue: 0.333333, alpha: 1.000000)
  }

  static func blueButtonColor() -> UIColor {
    return UIColor(red: 0.000000, green: 0.478431, blue: 1.000000, alpha: 1.000000)
  }

  static func blueButtonHighlightedBackgroundColor() -> UIColor {
    return UIColor(red: 0.082353, green: 0.627451, blue: 1.000000, alpha: 1.000000)
  }

  static func formTextFieldDarkGrayBackgroundColor() -> UIColor {
    return UIColor(red: 0.403922, green: 0.403922, blue: 0.403922, alpha: 1.000000)
  }

  static func formTextFieldLightGrayBackgroundColor() -> UIColor {
    return UIColor(red: 0.568627, green: 0.568627, blue: 0.568627, alpha: 1.000000)
  }

  static func formTextFieldPlaceholderColor() -> UIColor {
    return UIColor(red: 1.000000, green: 1.000000, blue: 1.000000, alpha: 0.600000)
  }

  static func whiteTextColor() -> UIColor {
    return UIColor(red: 1.000000, green: 1.000000, blue: 1.000000, alpha: 1.000000)
  }

  static func invalidFormTextFieldIndicatorColor() -> UIColor {
    return UIColor(red: 0.862745, green: 0.000000, blue: 0.000000, alpha: 1.000000)
  }

}
